CampeonatoBrasileiro/Controllers/JogoController.cs
using CampeonatoBrasileiro.Models;
using CampeonatoBrasileiro.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CampeonatoBrasileiro.Controllers
{
    public class JogoController : Controller
    {
        // GET: Jogo
        public ActionResult Index(int gameId)
        {
            BoxScore jogo = Campeonato.GetBoxScore(gameId);
            return View(jogo);
        }
    }
}

CampeonatoBrasileiro/Views/Shared/_Artilharia.cshtml
@model IEnumerable<CampeonatoBrasileiro.Models.PlayerSeason>

<table class="table">
    <tr>
        <th colspan="3">RANKING</th>
        <th>GOLS</th>
    </tr>
@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Team)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Position)
        </td>
        <td>
            <strong>@Html.DisplayFor(modelItem => item.Name)</strong>
        </td>
        <td>
            <h1>@(Math.Truncate(item.Goals.Value)</h1>
        </td>
    </tr>
}

</table>

CampeonatoBrasileiro/Views/Shared/_Jogos.cshtml
@model IEnumerable<CampeonatoBrasileiro.Models.Game>

<table class="table">
    <tr>
        <th>
            
        </th>
        <th colspan="3">
            @Model.FirstOrDefault().Week ª RODADA
        </th>
        <th>
            
        </th>
    </tr>

@foreach (var item in Model)
{
    <tr>
        <td colspan="5">
            <small>@Html.DisplayFor(modelItem => item.DateTime)</small>  
        </td>
    </tr>
    <tr>
        <td>
            <img src="@item.HomeTeam.WikipediaLogoUrl" height="30" width="30" alt="@item.HomeTeamName"/>
        </td>
        <td>
            <strong>@item.HomeTeamScore</strong> 
        </td>
        <td>
            X
        </td>
        <td>
            <strong>@item.AwayTeamScore</strong>
        </td>
        <td>
            <img src="@item.AwayTeam.WikipediaLogoUrl" height="30" width="30" alt="@item.AwayTeamName"/>
        </td>
    </tr>
    <tr>
        <td colspan="5">
          <small>@Html.ActionLink("VEJA COMO FOI","Index","Jogo", new { gameid = item.GameId }, null)</small>
        </td>
    </tr>
}
</table>

CampeonatoBrasileiro/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - CallCenter MVC DDD</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <link href="~/Content/mystyle.css" type="text/css" rel="stylesheet" />
</head>
<body>
    <header>
        <nav class="navbar navbar-default navbar-fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Campeonato Brasileirão - Série A - 2017", "", "", new { area = "" }, new { @class = "navbar-brand" })
                </div>
                <div class="collapse navbar-collapse">
                    <ul class="nav navbar-nav">
                        <li>@Html.ActionLink("Classificação", "Index", "Classificacao")</li>
                        <li>@Html.ActionLink("Jogos", "Index", "Jogo")</li>
                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="#"><span class="glyphicon glyphicon-log-out"></span> Sair</a></li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>